import { RegionConfigMap } from '@/types/region';

export const regionConfig: RegionConfigMap = {
  koshinetsu: {
    name: '甲信越',
    emoji: '🗻',
    color: 'from-purple-50 to-violet-100',
    borderColor: 'border-white/60',
    description: '甲信越地区以雄伟的山脉和雪景而闻名。',
    gridArea: 'koshinetsu',
    icons: {
      hanabi: '🎆',
      spots: '🏔️',
      events: '🎿',
      food: '🍇',
    },
  },
  kitakanto: {
    name: '北关东',
    emoji: '♨️',
    color: 'from-green-50 to-emerald-100',
    borderColor: 'border-white/60',
    description: '北关东地区拥有壮丽的自然风光和温泉。',
    gridArea: 'kitakanto',
    icons: {
      hanabi: '🎆',
      spots: '♨️',
      events: '🏯',
      food: '🥟',
    },
  },
  saitama: {
    name: '埼玉县',
    emoji: '🌸',
    color: 'from-orange-50 to-amber-100',
    borderColor: 'border-white/60',
    description: '在埼玉感受宁静的自然与传统祭典。',
    gridArea: 'saitama',
    icons: {
      hanabi: '🎆',
      spots: '🏰',
      events: '🎭',
      food: '🍜',
    },
  },
  chiba: {
    name: '千叶县',
    emoji: '🌊',
    color: 'from-sky-50 to-cyan-100',
    borderColor: 'border-white/60',
    description: '千叶拥有美丽的海岸线和丰富的自然景观。',
    gridArea: 'chiba',
    icons: {
      hanabi: '🎆',
      spots: '🏖️',
      events: '🎪',
      food: '🦐',
    },
  },
  tokyo: {
    name: '东京都',
    emoji: '🗼',
    color: 'from-red-50 to-rose-100',
    borderColor: 'border-white/60',
    description: '探索东京的繁华都市与传统文化。',
    gridArea: 'tokyo',
    icons: {
      hanabi: '🎆',
      spots: '🗼',
      events: '🎭',
      food: '🍣',
    },
  },
  kanagawa: {
    name: '神奈川',
    emoji: '⛵',
    color: 'from-blue-100 to-blue-200',
    borderColor: 'border-white/60',
    description: '在神奈川体验海滨风光与历史名城。',
    gridArea: 'kanagawa',
    icons: {
      hanabi: '🎆',
      spots: '⛩️',
      events: '🌺',
      food: '��',
    },
  },
};
