/**
 * 第三层页面 - 埼玉花火大会列表
 * @layer 三层 (Category Layer)
 * @category 花火
 * @region 埼玉
 * @description 展示埼玉地区所有花火大会，支持日期筛选和红心互动
 * @template HanabiPageTemplate.tsx
 * @dataSource WalkerPlus - https://hanabi.walkerplus.com/launch/ar0311/
 */

import { Metadata } from 'next';
import HanabiPageTemplate from '../../../components/HanabiPageTemplate';

export const metadata: Metadata = {
  title: '埼玉花火大会2025 - 戸田橋熊谷朝霞等精彩花火祭典完整攻略',
  description:
    '埼玉地区2025年花火大会完整指南，包含戸田橋花火大会、熊谷花火大会、朝霞彩夏祭等精彩活动。提供详细的时间、地点、观赏攻略，助您规划完美的埼玉花火之旅。',
  keywords: [
    '埼玉花火大会',
    '戸田橋花火大会',
    '熊谷花火',
    '朝霞彩夏祭',
    '埼玉旅游',
    '2025花火',
    '关东花火',
    '夏日祭典',
    '日本花火',
    '埼玉观光',
  ],
  openGraph: {
    title: '埼玉花火大会2025 - 戸田橋熊谷朝霞等精彩花火祭典完整攻略',
    description:
      '埼玉地区2025年花火大会完整指南，戸田橋花火大会、熊谷花火大会等精彩活动等您来体验。',
    type: 'website',
    url: 'https://www.kanto-travel-guide.com/saitama/hanabi',
    siteName: '关东旅游指南',
    images: [
      {
        url: 'https://www.kanto-travel-guide.com/images/saitama-hanabi-og.jpg',
        width: 1200,
        height: 630,
        alt: '埼玉花火大会2025',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: '埼玉花火大会2025 - 戸田橋熊谷朝霞等精彩花火祭典完整攻略',
    description:
      '埼玉地区2025年花火大会完整指南，戸田橋花火大会、熊谷花火大会等精彩活动等您来体验。',
    images: [
      'https://www.kanto-travel-guide.com/images/saitama-hanabi-twitter.jpg',
    ],
  },
  alternates: {
    canonical: 'https://www.kanto-travel-guide.com/saitama/hanabi',
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};

// 埼玉花火数据（共13场活动）
// 数据统计：声明活动数量=13场，实际活动数组长度=13场 ✅ 一致
const saitamaHanabiEvents = [
  {
    id: 'metsza-nordic-2025',
    name: '梅兹的北欧花火2025',
    title: '梅兹的北欧花火2025',
    _sourceData: {
      japaneseName: '梅兹北欧花火2025',
      japaneseDescription: '梅兹北欧花火2025',
    },
    englishName: 'Metsa Nordic Fireworks 2025',
    date: '2025年7月12日',
    location: '梅兹(梅兹村·姆明谷公园)',
    description: '北欧风格的现代花火，在都市夜景中展现独特魅力',
    features: ['北欧风格', '现代花火', '都市夜景'],
    likes: 8,
    website: 'https://metsa-hanno.com/',
    fireworks: '未公布',
    fireworksCount: '未公布',
    fireworksCountNum: null,
    visitors: '未公布',
    expectedVisitors: '未公布',
    expectedVisitorsNum: null,
    venue: '梅兹(梅兹村·姆明谷公园)',
    detailLink: '/saitama/hanabi/metsza-nordic-2025',
  },
  {
    id: 'seibu-daika-matsuri',
    name: '西武园游乐园大火祭',
    title: '西武园游乐园大火祭',
    _sourceData: {
      japaneseName: '西武園游乐园大火祭',
      japaneseDescription: '西武園游乐园大火祭',
    },
    englishName: 'Seibuenchi Amusement Park Great Fire Festival',
    date: '2025年7月19日～9月15日',
    location: '西武园游乐园',
    description: '音乐花火与夜间祭典的大迫力演出，体验游乐园独特的花火盛典',
    features: ['音乐花火', '夜间祭典', '大迫力演出'],
    likes: 30,
    website: 'https://www.seibu-leisure.co.jp/',
    fireworks: '未公布',
    fireworksCount: '未公布',
    fireworksCountNum: null,
    visitors: '未公布',
    expectedVisitors: '未公布',
    expectedVisitorsNum: null,
    venue: '西武园游乐园',
    detailLink: '/saitama/hanabi/seibu-en-2025',
  },
  {
    id: 'iruma-kichi-2025',
    name: '令和7年度入间基地纳凉祭～盆踊与花火之夕～',
    title: '令和7年度入间基地纳凉祭～盆踊与花火之夕～',
    _sourceData: {
      japaneseName: '令和7年度入間基地納涼祭～盆踊与花火之夕～',
      japaneseDescription: '令和7年度入間基地納涼祭～盆踊与花火之夕～',
    },
    englishName: 'Iruma Airbase Summer Festival 2025',
    date: '2025年7月23日',
    location: '航空自卫队入间基地',
    description: '在自卫队基地举办的特殊花火祭典，观赏4号玉星型烟花的壮观演出',
    features: ['自卫队基地', '4号玉', '星型烟花'],
    likes: 20,
    website: 'https://www.mod.go.jp/',
    fireworks: '約900発',
    fireworksCount: '約900発',
    fireworksCountNum: 900,
    visitors: '約4万2000人',
    expectedVisitors: '約4万2000人',
    expectedVisitorsNum: 42000,
    venue: '航空自卫队入间基地',
    detailLink: '/saitama/hanabi/iruma-base-2025',
  },
  {
    id: 'koshigaya-hanabi',
    name: '越谷花火大会',
    _sourceData: {
      japaneseName: '越谷花火大会',
      japaneseDescription: '越谷花火大会',
    },
    englishName: 'Koshigaya Fireworks Festival',
    date: '2025年7月26日',
    location: '越谷市中央市民会馆葛西用水中土手',
    description: '多样花火在夏夜绚烂绽放，是越谷市民热爱的传统祭典',
    features: ['多样花火', '夏夜绚烂', '市民祭典'],
    likes: 88,
    website: 'https://www.city.koshigaya.saitama.jp/',
    fireworksCount: '約5000発',
    fireworksCountNum: 5000,
    expectedVisitors: '約27万人',
    expectedVisitorsNum: 270000,
    venue: '越谷市中央市民会馆葛西用水中土手',
    detailLink: '/saitama/hanabi/koshigaya-2025',
  },
  {
    id: 'ogawa-tanabata-2025',
    name: '小川町七夕祭花火大会',
    _sourceData: {
      japaneseName: '小川町七夕祭花火大会',
      japaneseDescription: '小川町七夕祭花火大会',
    },
    englishName: 'Ogawa Town Tanabata Festival Fireworks',
    date: '2025年7月26日',
    location: '小川町站周边',
    description: '七夕花火与传统祭典结合，在山间展现独特的花火文化',
    features: ['七夕花火', '传统祭典', '山间花火'],
    likes: 25,
    website: 'https://www.town.ogawa.saitama.jp/',
    fireworksCount: '約200発',
    fireworksCountNum: 200,
    expectedVisitors: '約9万人',
    expectedVisitorsNum: 90000,
    venue: '小川町站周边',
    detailLink: '/saitama/hanabi/ogawa-tanabata-2025',
  },
  {
    id: 'saitama-yamato-2025',
    name: '令和7年度 埼玉市花火大会 大和田公园会场',
    _sourceData: {
      japaneseName: '令和7年度 埼玉市花火大会 大和田公園会場',
      japaneseDescription: '令和7年度 埼玉市花火大会 大和田公園会場',
    },
    englishName: 'Saitama City Fireworks Festival - Owada Park Venue',
    date: '2025年7月27日',
    location: '大和田公园周边',
    description: '埼玉系列花火大会的夏季开幕，在公园环境中享受花火观赏',
    features: ['埼玉系列', '公园观赏', '夏季开幕'],
    likes: 33,
    website: 'https://www.city.saitama.jp/',
    fireworksCount: '未定',
    fireworksCountNum: null,
    expectedVisitors: '約9万人',
    expectedVisitorsNum: 90000,
    venue: '大和田公园周边',
    detailLink: '/saitama/hanabi/saitama-owada-2025',
  },
  {
    id: 'todabashi-sky-fantasia-72',
    name: '第72回 戸田橋花火大会 Sky Fantasia',
    title: '第72回 戸田橋花火大会 Sky Fantasia',
    _sourceData: {
      japaneseName: '第72回 戸田橋花火大会 Sky Fantasia',
      japaneseDescription: '第72回 戸田橋花火大会 Sky Fantasia',
    },
    englishName: '72nd Todabashi Fireworks Festival Sky Fantasia',
    date: '2025年8月2日',
    location: '国道17号戸田橋上流荒川河川敷',
    description: '双城同步的日本唯一光之竞演，规模宏大的河川敷花火盛典',
    features: ['双城同步', '日本唯一', '光之竞演'],
    likes: 75,
    website: 'https://www.city.toda.saitama.jp/',
    fireworks: '約1万5000発',
    fireworksCount: '約1万5000発',
    fireworksCountNum: 15000,
    visitors: '約45万人',
    expectedVisitors: '約45万人',
    expectedVisitorsNum: 450000,
    venue: '国道17号戸田橋上流荒川河川敷',
    detailLink: '/saitama/hanabi/todabashi',
  },
  {
    id: 'asaka-saika-matsuri',
    name: '朝霞市民祭典「彩夏祭」',
    _sourceData: {
      japaneseName: '朝霞市民祭典「彩夏祭」',
      japaneseDescription: '朝霞市民祭典「彩夏祭」',
    },
    englishName: 'Asaka Citizens Festival "Saika Matsuri"',
    date: '2025年8月2日',
    location: '朝霞营跡地',
    description: '祭典花火与光音共演的迫力满点演出，朝霞市最大的市民节庆',
    features: ['祭典花火', '光音共演', '迫力满点'],
    likes: 25,
    website: 'https://www.city.asaka.lg.jp/',
    fireworksCount: '約9000発',
    fireworksCountNum: 9000,
    expectedVisitors: '約73万人',
    expectedVisitorsNum: 730000,
    venue: '朝霞营跡地',
    detailLink: '/saitama/hanabi/asaka',
  },
  {
    id: 'sayama-tanabata-2025',
    name: '狭山市入间川七夕祭纳凉花火大会',
    _sourceData: {
      japaneseName: '狭山市入間川七夕祭典纳凉花火大会',
      japaneseDescription: '狭山市入間川七夕祭典纳凉花火大会',
    },
    englishName: 'Sayama Iruma River Tanabata Cool Fireworks',
    date: '2025年8月2日',
    location: '入间川河川敷',
    description: '竹饰花火与七夕祭典结合，在河川敷享受传统夏日风情',
    features: ['竹饰花火', '七夕祭典', '河川敷花火'],
    likes: 6,
    website: 'https://www.city.sayama.saitama.jp/',
    fireworksCount: '約2000発',
    fireworksCountNum: 2000,
    expectedVisitors: '未公布',
    expectedVisitorsNum: null,
    venue: '入间川河川敷',
    detailLink: '/saitama/hanabi/sayama-tanabata',
  },
  {
    id: 'kumagaya-hanabi',
    name: '熊谷花火大会',
    _sourceData: {
      japaneseName: '熊谷花火大会',
      japaneseDescription: '熊谷花火大会',
    },
    englishName: 'Kumagaya Fireworks Festival',
    date: '2025年8月9日',
    location: '荒川河畔(荒川大桥下流)',
    description: '心意信息与花火共演，在荒川河畔展现壮观的花火盛典',
    features: ['心意信息', '花火共演', '荒川河畔'],
    likes: 33,
    website: 'https://www.city.kumagaya.lg.jp/',
    fireworksCount: '約1万発',
    fireworksCountNum: 10000,
    expectedVisitors: '約42万人',
    expectedVisitorsNum: 420000,
    venue: '荒川河畔(荒川大桥下流)',
    detailLink: '/saitama/hanabi/kumagaya',
  },
  {
    id: 'higashimatsuyama-26',
    name: '第26回 东松山花火大会',
    _sourceData: {
      japaneseName: '第26回 东松山花火大会',
      japaneseDescription: '第26回 东松山花火大会',
    },
    englishName: '26th Higashimatsuyama Fireworks Festival',
    date: '2025年8月23日',
    location: '都几川河边公园',
    description: '近距离观赏迫力满点的河边花火，体验东松山独特的花火魅力',
    features: ['近距离观赏', '迫力满点', '河边花火'],
    likes: 80,
    website: 'https://www.city.higashimatsuyama.lg.jp/',
    fireworksCount: '約5000発',
    fireworksCountNum: 5000,
    expectedVisitors: '約6万人',
    expectedVisitorsNum: 60000,
    venue: '都几川河边公园',
    detailLink: '/saitama/hanabi/higashimatsuyama',
  },
  {
    id: 'ina-matsuri-2025',
    name: '2025 伊奈祭',
    _sourceData: {
      japaneseName: '2025 伊奈祭典',
      japaneseDescription: '2025 伊奈祭典',
    },
    englishName: '2025 Ina Festival',
    date: '2025年8月23日',
    location: '伊奈町制施行记念公园',
    description: '玫瑰之町的鲜艳花火，伊奈町制施行记念公园的町祭花火',
    features: ['玫瑰之町', '鲜艳花火', '町祭花火'],
    likes: 20,
    website: 'https://www.town.ina.saitama.jp/',
    fireworksCount: '未公布',
    fireworksCountNum: null,
    expectedVisitors: '約4万人',
    expectedVisitorsNum: 40000,
    venue: '伊奈町制施行记念公园',
    detailLink: '/saitama/hanabi/ina',
  },
  {
    id: 'kounosu-shoukoukai-22',
    name: '燃烧吧！商工会青年部！！第22回 鸿巢花火大会',
    _sourceData: {
      japaneseName: '燃燃烧!商工会青年部!!第22回 鸿巢花火大会',
      japaneseDescription: '燃燃烧!商工会青年部!!第22回 鸿巢花火大会',
    },
    englishName: '22nd Konosu Fireworks Festival',
    date: '2025年10月11日',
    location: '糠田运动场及荒川河川敷',
    description: '创造世界记录的4尺玉特大花火，展现前所未有的花火壮观',
    features: ['世界记录', '4尺玉', '特大花火'],
    likes: 64,
    website: 'https://www.city.konosu.saitama.jp/',
    fireworksCount: '約2万発',
    fireworksCountNum: 20000,
    expectedVisitors: '約60万人',
    expectedVisitorsNum: 600000,
    venue: '糠田运动场及荒川河川敷',
    detailLink: '/saitama/hanabi/kounosu-shoukoukai-22',
  },
];

// 埼玉地区配置
const saitamaRegionConfig = {
  name: 'saitama',
  displayName: '埼玉',
  emoji: '🌾',
  description: '田园花火与都市文化的完美融合，感受埼玉独特的花火魅力',
  navigationLinks: {
    prev: { name: '东京', url: '/tokyo/hanabi', emoji: '🗼' },
    next: { name: '千叶', url: '/chiba/hanabi', emoji: '🌊' },
    current: { name: '埼玉', url: '/saitama' },
  },
};

export default function SaitamaHanabiPage() {
  return (
    <HanabiPageTemplate
      region={saitamaRegionConfig}
      events={saitamaHanabiEvents}
      regionKey="saitama"
      activityKey="hanabi"
      pageTitle="埼玉花火大会列表"
      pageDescription="体验埼玉地区最精彩的花火大会，从北欧风格的梅兹花火到世界记录的鸿巢花火，感受田园与都市交融的花火文化"
    />
  );
}
